// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/speech/v1p1beta1/cloud_speech_adaptation.proto

package com.google.cloud.speech.v1p1beta1;

public interface CreateCustomClassRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.speech.v1p1beta1.CreateCustomClassRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The parent resource where this custom class will be created.
   * Format:
   * {api_version}/projects/{project}/locations/{location}/customClasses
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * Required. The parent resource where this custom class will be created.
   * Format:
   * {api_version}/projects/{project}/locations/{location}/customClasses
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();

  /**
   * <pre>
   * Required. The ID to use for the custom class, which will become the final
   * component of the custom class' resource name.
   * This value should be 4-63 characters, and valid characters
   * are /[a-z][0-9]-/.
   * </pre>
   *
   * <code>string custom_class_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The customClassId.
   */
  java.lang.String getCustomClassId();
  /**
   * <pre>
   * Required. The ID to use for the custom class, which will become the final
   * component of the custom class' resource name.
   * This value should be 4-63 characters, and valid characters
   * are /[a-z][0-9]-/.
   * </pre>
   *
   * <code>string custom_class_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for customClassId.
   */
  com.google.protobuf.ByteString
      getCustomClassIdBytes();

  /**
   * <pre>
   * Required. The custom class to create.
   * </pre>
   *
   * <code>.google.cloud.speech.v1p1beta1.CustomClass custom_class = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the customClass field is set.
   */
  boolean hasCustomClass();
  /**
   * <pre>
   * Required. The custom class to create.
   * </pre>
   *
   * <code>.google.cloud.speech.v1p1beta1.CustomClass custom_class = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The customClass.
   */
  com.google.cloud.speech.v1p1beta1.CustomClass getCustomClass();
  /**
   * <pre>
   * Required. The custom class to create.
   * </pre>
   *
   * <code>.google.cloud.speech.v1p1beta1.CustomClass custom_class = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.cloud.speech.v1p1beta1.CustomClassOrBuilder getCustomClassOrBuilder();
}
