// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/speech/v1p1beta1/cloud_speech_adaptation.proto

package com.google.cloud.speech.v1p1beta1;

public interface UpdatePhraseSetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.speech.v1p1beta1.UpdatePhraseSetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The phrase set to update.
   * The phrase set's `name` field is used to identify the set to be
   * updated. Format:
   * {api_version}/projects/{project}/locations/{location}/phraseSets/{phrase_set}
   * </pre>
   *
   * <code>.google.cloud.speech.v1p1beta1.PhraseSet phrase_set = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the phraseSet field is set.
   */
  boolean hasPhraseSet();
  /**
   * <pre>
   * Required. The phrase set to update.
   * The phrase set's `name` field is used to identify the set to be
   * updated. Format:
   * {api_version}/projects/{project}/locations/{location}/phraseSets/{phrase_set}
   * </pre>
   *
   * <code>.google.cloud.speech.v1p1beta1.PhraseSet phrase_set = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The phraseSet.
   */
  com.google.cloud.speech.v1p1beta1.PhraseSet getPhraseSet();
  /**
   * <pre>
   * Required. The phrase set to update.
   * The phrase set's `name` field is used to identify the set to be
   * updated. Format:
   * {api_version}/projects/{project}/locations/{location}/phraseSets/{phrase_set}
   * </pre>
   *
   * <code>.google.cloud.speech.v1p1beta1.PhraseSet phrase_set = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.cloud.speech.v1p1beta1.PhraseSetOrBuilder getPhraseSetOrBuilder();

  /**
   * <pre>
   * The list of fields to be updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   * @return Whether the updateMask field is set.
   */
  boolean hasUpdateMask();
  /**
   * <pre>
   * The list of fields to be updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   * @return The updateMask.
   */
  com.google.protobuf.FieldMask getUpdateMask();
  /**
   * <pre>
   * The list of fields to be updated.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder();
}
